name: Test Upload
run-name: Test Upload
on:
  workflow_dispatch:
  push:

jobs:
  test-upload:
    name: Test Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Action File
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            action.yml
          sparse-checkout-cone-mode: false

      - name: Create Mock Artifacts
        shell: bash
        run: |
          echo "This is a mock artifact" > file1.txt
          echo "This is another mock artifact" > file2.txt
          echo "This is a third mock artifact" > file3.txt

      - name: Run Action from File
        uses: ./
        with:
          source: file?.txt
          password: supersecretpassword
          compression-level: 5
          local-name: myartifact.tar.7z
          remote-name: myartifact
          retention-days: 7
          overwrite: true
